evaluationTime = 100

SCALING_FACTOR = 0.1


OBSTACLE_HEIGHT = 0.5 * SCALING_FACTOR

OBSTACLE_WIDTH = 2.0 * SCALING_FACTOR

OBSTACLE_LENGTH = 1.0 * SCALING_FACTOR


LIGHT_SOURCE_HEIGHT = OBSTACLE_HEIGHT / 10.0


ROBOT_HEIGHT = 0.25 * SCALING_FACTOR

ROBOT_WIDTH = 0.5 * SCALING_FACTOR

ROBOT_LENGTH = 0.75 * SCALING_FACTOR

WHEEL_RADIUS = ROBOT_HEIGHT/2.0
